stages:
  - test
  - build
  - deploy

.reactive-job:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

.cpython:3.8.2:
  before_script:
    - pip install nox 'virtualenv<20.0.19'
  image: python:3.8.2

black:
  extends: 
    - .cpython:3.8.2
    - .reactive-job
  script:
    - nox -s format
  stage: test

pages:
  extends:
    - .cpython:3.8.2
  script:
    - nox -s sphinx
    - mv docs/build public
  stage: build
  artifacts:
    paths:
      - public
  only:
    - master

pypi:
  environment:
    name: prod
    url: https://tandemdude.gitlab.io/lightbulb
  extends:
    - .cpython:3.8.2
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
  only:
    - master
