stages:
  - test

.reactive-job:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

.cpython:3.8.2:
  before_script:
    - pip install nox 'virtualenv<20.0.19'
  image: python:3.8.2

black:
  extends: 
    - .cpython:3.8.2
    - .reactive-job
  script:
    - nox -s format
  stage: test

pages:
  extends:
    - .cpython:3.8.2
  script:
    - nox -s sphinx
    - mv docs/build public
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
