stages:
  - test
  - deploy

.reactive-job:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

black:
  image: python:3.9
  extends: .reactive-job
  before_script: 
    - pip install nox
  script: 
    - nox -s format
  stage: test

pytest-cpython-3.8:
  image: python:3.8
  extends: .reactive-job
  before_script: 
    - pip install nox
  script: 
    - nox -s test
  stage: test

pytest-cpython-3.9:
  image: python:3.9
  extends: .reactive-job
  before_script: 
    - pip install nox
  script: 
    - nox -s test
  stage: test

deploy-dryrun:
  image: python:3.9
  extends: .reactive-job
  script: 
    - pip install -U requests setuptools twine wheel -r requirements.txt
    - python setup.py sdist bdist_wheel install
    - ls dist -rl
  stage: test

pages:
  image: python:3.9
  before_script: 
    - pip install nox
  script: 
    - nox -s sphinx && mv docs/build public
  stage: deploy
  artifacts:
    expire_in: 2 days
    paths:
      - public
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_REF_NAME == 'master'"
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $CI_COMMIT_REF_NAME == 'master'"

pypi:
  environment:
    name: prod
    url: https://tandemdude.gitlab.io/lightbulb
  image: python:3.9
  script:
    - pip install -U requests setuptools twine wheel -r requirements.txt
    - python setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*
    - python release_webhook.py
  stage: deploy
  only:
    - master
